apiVersion: v1
kind: Service
metadata:
  name: s03-nlb-service
  namespace: scenario03
  labels:
    app: s03-app
spec:
  selector:
    app: s03-app
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80