apiVersion: v1
kind: Service
metadata:
  name: s04-nlb-service
  namespace: scenario04
  labels:
    app: s04-app
spec:
  selector:
    app: s04-app
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080